apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  type: ClusterIP
  selector:
    app: vpromc
  ports:
  - port: 11211
    targetPort: vpromc-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
spec:
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
        - name: vpromc
          image: memcached
          ports:
          - name: vpromc-port
            containerPort: 11211
